# Generated by Django 5.0.4 on 2024-04-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
